backend:
  name: git-gateway
  branch: main

media_folder: images
public_folder: /images

collections:
  - name: candidates
    label: 候補シナリオ
    files:
      - name: candidates
        label: 候補シナリオページ
        file: candidates.html
        fields:
          - label: シナリオ一覧
            name: scenarios
            widget: list
            fields:
              - {label: タイトル, name: title, widget: string}
              - {label: ジャンル, name: genre, widget: string}
              - {label: 説明, name: description, widget: text}
              - {label: ポスター画像, name: image, widget: image, required: false}
